name = "ieee-sb-cek-esi"
compatibility_date = "2024-01-15"

# Cloudflare Pages configuration
pages_build_output_dir = "./"

# Environment variables (Pages supports preview and production only)
[env.production]
compatibility_date = "2024-01-15"

[env.preview]
compatibility_date = "2024-01-15"