name = "ieee-sb-cek-esi"
main = "functions/_worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "./"

# Environment variables (if needed)
[env.production]
name = "ieee-sb-cek-esi-prod"

[env.staging]
name = "ieee-sb-cek-esi-staging"

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "ESI_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"